/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAClassDeclsProgram(AClassDeclsProgram node)
    {
        defaultIn(node);
    }

    public void outAClassDeclsProgram(AClassDeclsProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClassDeclsProgram(AClassDeclsProgram node)
    {
        inAClassDeclsProgram(node);
        if(node.getClassDecls() != null)
        {
            node.getClassDecls().apply(this);
        }
        outAClassDeclsProgram(node);
    }

    public void inAMultClassDeclClassDecls(AMultClassDeclClassDecls node)
    {
        defaultIn(node);
    }

    public void outAMultClassDeclClassDecls(AMultClassDeclClassDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultClassDeclClassDecls(AMultClassDeclClassDecls node)
    {
        inAMultClassDeclClassDecls(node);
        if(node.getClassDecl() != null)
        {
            node.getClassDecl().apply(this);
        }
        if(node.getClassDecls() != null)
        {
            node.getClassDecls().apply(this);
        }
        outAMultClassDeclClassDecls(node);
    }

    public void inASingleClassDeclClassDecls(ASingleClassDeclClassDecls node)
    {
        defaultIn(node);
    }

    public void outASingleClassDeclClassDecls(ASingleClassDeclClassDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleClassDeclClassDecls(ASingleClassDeclClassDecls node)
    {
        inASingleClassDeclClassDecls(node);
        if(node.getClassDecl() != null)
        {
            node.getClassDecl().apply(this);
        }
        outASingleClassDeclClassDecls(node);
    }

    public void inAEmptyClassDeclClassDecl(AEmptyClassDeclClassDecl node)
    {
        defaultIn(node);
    }

    public void outAEmptyClassDeclClassDecl(AEmptyClassDeclClassDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyClassDeclClassDecl(AEmptyClassDeclClassDecl node)
    {
        inAEmptyClassDeclClassDecl(node);
        if(node.getRBrace() != null)
        {
            node.getRBrace().apply(this);
        }
        if(node.getLBrace() != null)
        {
            node.getLBrace().apply(this);
        }
        if(node.getClassHdr() != null)
        {
            node.getClassHdr().apply(this);
        }
        outAEmptyClassDeclClassDecl(node);
    }

    public void inAClassDeclClassDecl(AClassDeclClassDecl node)
    {
        defaultIn(node);
    }

    public void outAClassDeclClassDecl(AClassDeclClassDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClassDeclClassDecl(AClassDeclClassDecl node)
    {
        inAClassDeclClassDecl(node);
        if(node.getRBrace() != null)
        {
            node.getRBrace().apply(this);
        }
        if(node.getMemberDecls() != null)
        {
            node.getMemberDecls().apply(this);
        }
        if(node.getLBrace() != null)
        {
            node.getLBrace().apply(this);
        }
        if(node.getClassHdr() != null)
        {
            node.getClassHdr().apply(this);
        }
        outAClassDeclClassDecl(node);
    }

    public void inAClassHdrClassHdr(AClassHdrClassHdr node)
    {
        defaultIn(node);
    }

    public void outAClassHdrClassHdr(AClassHdrClassHdr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClassHdrClassHdr(AClassHdrClassHdr node)
    {
        inAClassHdrClassHdr(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getKclass() != null)
        {
            node.getKclass().apply(this);
        }
        outAClassHdrClassHdr(node);
    }

    public void inAMultMemberDeclMemberDecls(AMultMemberDeclMemberDecls node)
    {
        defaultIn(node);
    }

    public void outAMultMemberDeclMemberDecls(AMultMemberDeclMemberDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultMemberDeclMemberDecls(AMultMemberDeclMemberDecls node)
    {
        inAMultMemberDeclMemberDecls(node);
        if(node.getMember() != null)
        {
            node.getMember().apply(this);
        }
        if(node.getMemberDecls() != null)
        {
            node.getMemberDecls().apply(this);
        }
        outAMultMemberDeclMemberDecls(node);
    }

    public void inASingleMemberDeclMemberDecls(ASingleMemberDeclMemberDecls node)
    {
        defaultIn(node);
    }

    public void outASingleMemberDeclMemberDecls(ASingleMemberDeclMemberDecls node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleMemberDeclMemberDecls(ASingleMemberDeclMemberDecls node)
    {
        inASingleMemberDeclMemberDecls(node);
        if(node.getMember() != null)
        {
            node.getMember().apply(this);
        }
        outASingleMemberDeclMemberDecls(node);
    }

    public void inAFieldMember(AFieldMember node)
    {
        defaultIn(node);
    }

    public void outAFieldMember(AFieldMember node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFieldMember(AFieldMember node)
    {
        inAFieldMember(node);
        if(node.getField() != null)
        {
            node.getField().apply(this);
        }
        outAFieldMember(node);
    }

    public void inAMethodMember(AMethodMember node)
    {
        defaultIn(node);
    }

    public void outAMethodMember(AMethodMember node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodMember(AMethodMember node)
    {
        inAMethodMember(node);
        if(node.getMethod() != null)
        {
            node.getMethod().apply(this);
        }
        outAMethodMember(node);
    }

    public void inANoMemberMember(ANoMemberMember node)
    {
        defaultIn(node);
    }

    public void outANoMemberMember(ANoMemberMember node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoMemberMember(ANoMemberMember node)
    {
        inANoMemberMember(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outANoMemberMember(node);
    }

    public void inAFieldDeclField(AFieldDeclField node)
    {
        defaultIn(node);
    }

    public void outAFieldDeclField(AFieldDeclField node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFieldDeclField(AFieldDeclField node)
    {
        inAFieldDeclField(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAFieldDeclField(node);
    }

    public void inAFieldDeclAndInitField(AFieldDeclAndInitField node)
    {
        defaultIn(node);
    }

    public void outAFieldDeclAndInitField(AFieldDeclAndInitField node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFieldDeclAndInitField(AFieldDeclAndInitField node)
    {
        inAFieldDeclAndInitField(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getEqualTo() != null)
        {
            node.getEqualTo().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAFieldDeclAndInitField(node);
    }

    public void inAArrDeclField(AArrDeclField node)
    {
        defaultIn(node);
    }

    public void outAArrDeclField(AArrDeclField node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrDeclField(AArrDeclField node)
    {
        inAArrDeclField(node);
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getIntegerParamOrValue() != null)
        {
            node.getIntegerParamOrValue().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAArrDeclField(node);
    }

    public void inABoolTypeType(ABoolTypeType node)
    {
        defaultIn(node);
    }

    public void outABoolTypeType(ABoolTypeType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABoolTypeType(ABoolTypeType node)
    {
        inABoolTypeType(node);
        if(node.getBool() != null)
        {
            node.getBool().apply(this);
        }
        outABoolTypeType(node);
    }

    public void inACharTypeType(ACharTypeType node)
    {
        defaultIn(node);
    }

    public void outACharTypeType(ACharTypeType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACharTypeType(ACharTypeType node)
    {
        inACharTypeType(node);
        if(node.getChar() != null)
        {
            node.getChar().apply(this);
        }
        outACharTypeType(node);
    }

    public void inAFloatTypeType(AFloatTypeType node)
    {
        defaultIn(node);
    }

    public void outAFloatTypeType(AFloatTypeType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFloatTypeType(AFloatTypeType node)
    {
        inAFloatTypeType(node);
        if(node.getFloat() != null)
        {
            node.getFloat().apply(this);
        }
        outAFloatTypeType(node);
    }

    public void inAIntTypeType(AIntTypeType node)
    {
        defaultIn(node);
    }

    public void outAIntTypeType(AIntTypeType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntTypeType(AIntTypeType node)
    {
        inAIntTypeType(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntTypeType(node);
    }

    public void inAStringTypeType(AStringTypeType node)
    {
        defaultIn(node);
    }

    public void outAStringTypeType(AStringTypeType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringTypeType(AStringTypeType node)
    {
        inAStringTypeType(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringTypeType(node);
    }

    public void inAMethodDeclMethod(AMethodDeclMethod node)
    {
        defaultIn(node);
    }

    public void outAMethodDeclMethod(AMethodDeclMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodDeclMethod(AMethodDeclMethod node)
    {
        inAMethodDeclMethod(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getFormals() != null)
        {
            node.getFormals().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMethodHdr() != null)
        {
            node.getMethodHdr().apply(this);
        }
        outAMethodDeclMethod(node);
    }

    public void inANoParamMethodDeclMethod(ANoParamMethodDeclMethod node)
    {
        defaultIn(node);
    }

    public void outANoParamMethodDeclMethod(ANoParamMethodDeclMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoParamMethodDeclMethod(ANoParamMethodDeclMethod node)
    {
        inANoParamMethodDeclMethod(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMethodHdr() != null)
        {
            node.getMethodHdr().apply(this);
        }
        outANoParamMethodDeclMethod(node);
    }

    public void inAMethodHdrDeclVoidMethodHdr(AMethodHdrDeclVoidMethodHdr node)
    {
        defaultIn(node);
    }

    public void outAMethodHdrDeclVoidMethodHdr(AMethodHdrDeclVoidMethodHdr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodHdrDeclVoidMethodHdr(AMethodHdrDeclVoidMethodHdr node)
    {
        inAMethodHdrDeclVoidMethodHdr(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getVoid() != null)
        {
            node.getVoid().apply(this);
        }
        outAMethodHdrDeclVoidMethodHdr(node);
    }

    public void inAMethodHdrDeclMethodHdr(AMethodHdrDeclMethodHdr node)
    {
        defaultIn(node);
    }

    public void outAMethodHdrDeclMethodHdr(AMethodHdrDeclMethodHdr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodHdrDeclMethodHdr(AMethodHdrDeclMethodHdr node)
    {
        inAMethodHdrDeclMethodHdr(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAMethodHdrDeclMethodHdr(node);
    }

    public void inAMultFormalFormals(AMultFormalFormals node)
    {
        defaultIn(node);
    }

    public void outAMultFormalFormals(AMultFormalFormals node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultFormalFormals(AMultFormalFormals node)
    {
        inAMultFormalFormals(node);
        if(node.getFormal() != null)
        {
            node.getFormal().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getFormals() != null)
        {
            node.getFormals().apply(this);
        }
        outAMultFormalFormals(node);
    }

    public void inASingleFormalFormals(ASingleFormalFormals node)
    {
        defaultIn(node);
    }

    public void outASingleFormalFormals(ASingleFormalFormals node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleFormalFormals(ASingleFormalFormals node)
    {
        inASingleFormalFormals(node);
        if(node.getFormal() != null)
        {
            node.getFormal().apply(this);
        }
        outASingleFormalFormals(node);
    }

    public void inAFormalDeclFormal(AFormalDeclFormal node)
    {
        defaultIn(node);
    }

    public void outAFormalDeclFormal(AFormalDeclFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFormalDeclFormal(AFormalDeclFormal node)
    {
        inAFormalDeclFormal(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAFormalDeclFormal(node);
    }

    public void inAArrFormalDeclFormal(AArrFormalDeclFormal node)
    {
        defaultIn(node);
    }

    public void outAArrFormalDeclFormal(AArrFormalDeclFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrFormalDeclFormal(AArrFormalDeclFormal node)
    {
        inAArrFormalDeclFormal(node);
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAArrFormalDeclFormal(node);
    }

    public void inABlockDeclBlock(ABlockDeclBlock node)
    {
        defaultIn(node);
    }

    public void outABlockDeclBlock(ABlockDeclBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlockDeclBlock(ABlockDeclBlock node)
    {
        inABlockDeclBlock(node);
        if(node.getRBrace() != null)
        {
            node.getRBrace().apply(this);
        }
        if(node.getStmts() != null)
        {
            node.getStmts().apply(this);
        }
        if(node.getLBrace() != null)
        {
            node.getLBrace().apply(this);
        }
        outABlockDeclBlock(node);
    }

    public void inAEmptyBlockBlock(AEmptyBlockBlock node)
    {
        defaultIn(node);
    }

    public void outAEmptyBlockBlock(AEmptyBlockBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEmptyBlockBlock(AEmptyBlockBlock node)
    {
        inAEmptyBlockBlock(node);
        if(node.getRBrace() != null)
        {
            node.getRBrace().apply(this);
        }
        if(node.getLBrace() != null)
        {
            node.getLBrace().apply(this);
        }
        outAEmptyBlockBlock(node);
    }

    public void inAMultStmtStmts(AMultStmtStmts node)
    {
        defaultIn(node);
    }

    public void outAMultStmtStmts(AMultStmtStmts node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultStmtStmts(AMultStmtStmts node)
    {
        inAMultStmtStmts(node);
        if(node.getS() != null)
        {
            node.getS().apply(this);
        }
        if(node.getStmts() != null)
        {
            node.getStmts().apply(this);
        }
        outAMultStmtStmts(node);
    }

    public void inAStmtStmts(AStmtStmts node)
    {
        defaultIn(node);
    }

    public void outAStmtStmts(AStmtStmts node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStmtStmts(AStmtStmts node)
    {
        inAStmtStmts(node);
        if(node.getS() != null)
        {
            node.getS().apply(this);
        }
        outAStmtStmts(node);
    }

    public void inAConditionCondition(AConditionCondition node)
    {
        defaultIn(node);
    }

    public void outAConditionCondition(AConditionCondition node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConditionCondition(AConditionCondition node)
    {
        inAConditionCondition(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAConditionCondition(node);
    }

    public void inALocalDeclOther(ALocalDeclOther node)
    {
        defaultIn(node);
    }

    public void outALocalDeclOther(ALocalDeclOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALocalDeclOther(ALocalDeclOther node)
    {
        inALocalDeclOther(node);
        if(node.getLocalDecl() != null)
        {
            node.getLocalDecl().apply(this);
        }
        outALocalDeclOther(node);
    }

    public void inAAssignmentOther(AAssignmentOther node)
    {
        defaultIn(node);
    }

    public void outAAssignmentOther(AAssignmentOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignmentOther(AAssignmentOther node)
    {
        inAAssignmentOther(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getEqualTo() != null)
        {
            node.getEqualTo().apply(this);
        }
        if(node.getFieldAccess() != null)
        {
            node.getFieldAccess().apply(this);
        }
        outAAssignmentOther(node);
    }

    public void inAMethodCallOther(AMethodCallOther node)
    {
        defaultIn(node);
    }

    public void outAMethodCallOther(AMethodCallOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodCallOther(AMethodCallOther node)
    {
        inAMethodCallOther(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getMethodCall() != null)
        {
            node.getMethodCall().apply(this);
        }
        outAMethodCallOther(node);
    }

    public void inAReturnVoidOther(AReturnVoidOther node)
    {
        defaultIn(node);
    }

    public void outAReturnVoidOther(AReturnVoidOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReturnVoidOther(AReturnVoidOther node)
    {
        inAReturnVoidOther(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getReturn() != null)
        {
            node.getReturn().apply(this);
        }
        outAReturnVoidOther(node);
    }

    public void inAReturnExprOther(AReturnExprOther node)
    {
        defaultIn(node);
    }

    public void outAReturnExprOther(AReturnExprOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReturnExprOther(AReturnExprOther node)
    {
        inAReturnExprOther(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getReturn() != null)
        {
            node.getReturn().apply(this);
        }
        outAReturnExprOther(node);
    }

    public void inABlockOther(ABlockOther node)
    {
        defaultIn(node);
    }

    public void outABlockOther(ABlockOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlockOther(ABlockOther node)
    {
        inABlockOther(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        outABlockOther(node);
    }

    public void inAWhileLoopOther(AWhileLoopOther node)
    {
        defaultIn(node);
    }

    public void outAWhileLoopOther(AWhileLoopOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileLoopOther(AWhileLoopOther node)
    {
        inAWhileLoopOther(node);
        if(node.getBlock() != null)
        {
            node.getBlock().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        outAWhileLoopOther(node);
    }

    public void inADoWhileLoopOther(ADoWhileLoopOther node)
    {
        defaultIn(node);
    }

    public void outADoWhileLoopOther(ADoWhileLoopOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADoWhileLoopOther(ADoWhileLoopOther node)
    {
        inADoWhileLoopOther(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getWhile() != null)
        {
            node.getWhile().apply(this);
        }
        if(node.getStmts() != null)
        {
            node.getStmts().apply(this);
        }
        if(node.getDo() != null)
        {
            node.getDo().apply(this);
        }
        outADoWhileLoopOther(node);
    }

    public void inANoStatementOther(ANoStatementOther node)
    {
        defaultIn(node);
    }

    public void outANoStatementOther(ANoStatementOther node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoStatementOther(ANoStatementOther node)
    {
        inANoStatementOther(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        outANoStatementOther(node);
    }

    public void inAAs1S(AAs1S node)
    {
        defaultIn(node);
    }

    public void outAAs1S(AAs1S node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAs1S(AAs1S node)
    {
        inAAs1S(node);
        if(node.getM() != null)
        {
            node.getM().apply(this);
        }
        outAAs1S(node);
    }

    public void inAAs2S(AAs2S node)
    {
        defaultIn(node);
    }

    public void outAAs2S(AAs2S node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAs2S(AAs2S node)
    {
        inAAs2S(node);
        if(node.getU() != null)
        {
            node.getU().apply(this);
        }
        outAAs2S(node);
    }

    public void inAAm1M(AAm1M node)
    {
        defaultIn(node);
    }

    public void outAAm1M(AAm1M node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAm1M(AAm1M node)
    {
        inAAm1M(node);
        if(node.getM2() != null)
        {
            node.getM2().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getM1() != null)
        {
            node.getM1().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAAm1M(node);
    }

    public void inAAm2M(AAm2M node)
    {
        defaultIn(node);
    }

    public void outAAm2M(AAm2M node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAm2M(AAm2M node)
    {
        inAAm2M(node);
        if(node.getOther() != null)
        {
            node.getOther().apply(this);
        }
        outAAm2M(node);
    }

    public void inAAu1U(AAu1U node)
    {
        defaultIn(node);
    }

    public void outAAu1U(AAu1U node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAu1U(AAu1U node)
    {
        inAAu1U(node);
        if(node.getS() != null)
        {
            node.getS().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAAu1U(node);
    }

    public void inAAu2U(AAu2U node)
    {
        defaultIn(node);
    }

    public void outAAu2U(AAu2U node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAu2U(AAu2U node)
    {
        inAAu2U(node);
        if(node.getU2() != null)
        {
            node.getU2().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getU1() != null)
        {
            node.getU1().apply(this);
        }
        if(node.getCondition() != null)
        {
            node.getCondition().apply(this);
        }
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        outAAu2U(node);
    }

    public void inAVarDeclLocalDecl(AVarDeclLocalDecl node)
    {
        defaultIn(node);
    }

    public void outAVarDeclLocalDecl(AVarDeclLocalDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclLocalDecl(AVarDeclLocalDecl node)
    {
        inAVarDeclLocalDecl(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAVarDeclLocalDecl(node);
    }

    public void inAVarDeclAndInitLocalDecl(AVarDeclAndInitLocalDecl node)
    {
        defaultIn(node);
    }

    public void outAVarDeclAndInitLocalDecl(AVarDeclAndInitLocalDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDeclAndInitLocalDecl(AVarDeclAndInitLocalDecl node)
    {
        inAVarDeclAndInitLocalDecl(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getEqualTo() != null)
        {
            node.getEqualTo().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAVarDeclAndInitLocalDecl(node);
    }

    public void inAArrDeclLocalDecl(AArrDeclLocalDecl node)
    {
        defaultIn(node);
    }

    public void outAArrDeclLocalDecl(AArrDeclLocalDecl node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrDeclLocalDecl(AArrDeclLocalDecl node)
    {
        inAArrDeclLocalDecl(node);
        if(node.getSemicolon() != null)
        {
            node.getSemicolon().apply(this);
        }
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getIntegerParamOrValue() != null)
        {
            node.getIntegerParamOrValue().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outAArrDeclLocalDecl(node);
    }

    public void inAIdentifierFieldAccessFieldAccess(AIdentifierFieldAccessFieldAccess node)
    {
        defaultIn(node);
    }

    public void outAIdentifierFieldAccessFieldAccess(AIdentifierFieldAccessFieldAccess node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentifierFieldAccessFieldAccess(AIdentifierFieldAccessFieldAccess node)
    {
        inAIdentifierFieldAccessFieldAccess(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAIdentifierFieldAccessFieldAccess(node);
    }

    public void inAIdentifierArrayAccessFieldAccess(AIdentifierArrayAccessFieldAccess node)
    {
        defaultIn(node);
    }

    public void outAIdentifierArrayAccessFieldAccess(AIdentifierArrayAccessFieldAccess node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentifierArrayAccessFieldAccess(AIdentifierArrayAccessFieldAccess node)
    {
        inAIdentifierArrayAccessFieldAccess(node);
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getIntegerLiteral() != null)
        {
            node.getIntegerLiteral().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAIdentifierArrayAccessFieldAccess(node);
    }

    public void inAIdentifierEmptyArrayAccessFieldAccess(AIdentifierEmptyArrayAccessFieldAccess node)
    {
        defaultIn(node);
    }

    public void outAIdentifierEmptyArrayAccessFieldAccess(AIdentifierEmptyArrayAccessFieldAccess node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentifierEmptyArrayAccessFieldAccess(AIdentifierEmptyArrayAccessFieldAccess node)
    {
        inAIdentifierEmptyArrayAccessFieldAccess(node);
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAIdentifierEmptyArrayAccessFieldAccess(node);
    }

    public void inAArrayFieldAccessFieldAccess(AArrayFieldAccessFieldAccess node)
    {
        defaultIn(node);
    }

    public void outAArrayFieldAccessFieldAccess(AArrayFieldAccessFieldAccess node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayFieldAccessFieldAccess(AArrayFieldAccessFieldAccess node)
    {
        inAArrayFieldAccessFieldAccess(node);
        if(node.getRBkt() != null)
        {
            node.getRBkt().apply(this);
        }
        if(node.getFieldAccess() != null)
        {
            node.getFieldAccess().apply(this);
        }
        if(node.getLBkt() != null)
        {
            node.getLBkt().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAArrayFieldAccessFieldAccess(node);
    }

    public void inAFieldExtensionFieldAccess(AFieldExtensionFieldAccess node)
    {
        defaultIn(node);
    }

    public void outAFieldExtensionFieldAccess(AFieldExtensionFieldAccess node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFieldExtensionFieldAccess(AFieldExtensionFieldAccess node)
    {
        inAFieldExtensionFieldAccess(node);
        if(node.getFieldAccess() != null)
        {
            node.getFieldAccess().apply(this);
        }
        if(node.getDot() != null)
        {
            node.getDot().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFieldExtensionFieldAccess(node);
    }

    public void inAMethodCallNoArgMethodCall(AMethodCallNoArgMethodCall node)
    {
        defaultIn(node);
    }

    public void outAMethodCallNoArgMethodCall(AMethodCallNoArgMethodCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodCallNoArgMethodCall(AMethodCallNoArgMethodCall node)
    {
        inAMethodCallNoArgMethodCall(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getFieldAccess() != null)
        {
            node.getFieldAccess().apply(this);
        }
        outAMethodCallNoArgMethodCall(node);
    }

    public void inAMethodCallWithArgMethodCall(AMethodCallWithArgMethodCall node)
    {
        defaultIn(node);
    }

    public void outAMethodCallWithArgMethodCall(AMethodCallWithArgMethodCall node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMethodCallWithArgMethodCall(AMethodCallWithArgMethodCall node)
    {
        inAMethodCallWithArgMethodCall(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getArgs() != null)
        {
            node.getArgs().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getFieldAccess() != null)
        {
            node.getFieldAccess().apply(this);
        }
        outAMethodCallWithArgMethodCall(node);
    }

    public void inAMultArgArgs(AMultArgArgs node)
    {
        defaultIn(node);
    }

    public void outAMultArgArgs(AMultArgArgs node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultArgArgs(AMultArgArgs node)
    {
        inAMultArgArgs(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getArgs() != null)
        {
            node.getArgs().apply(this);
        }
        outAMultArgArgs(node);
    }

    public void inASingleArgArgs(ASingleArgArgs node)
    {
        defaultIn(node);
    }

    public void outASingleArgArgs(ASingleArgArgs node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleArgArgs(ASingleArgArgs node)
    {
        inASingleArgArgs(node);
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outASingleArgArgs(node);
    }

    public void inAOrOperationExpr(AOrOperationExpr node)
    {
        defaultIn(node);
    }

    public void outAOrOperationExpr(AOrOperationExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrOperationExpr(AOrOperationExpr node)
    {
        inAOrOperationExpr(node);
        if(node.getAndOperation() != null)
        {
            node.getAndOperation().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        outAOrOperationExpr(node);
    }

    public void inAMissingOrExpr(AMissingOrExpr node)
    {
        defaultIn(node);
    }

    public void outAMissingOrExpr(AMissingOrExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMissingOrExpr(AMissingOrExpr node)
    {
        inAMissingOrExpr(node);
        if(node.getAndOperation() != null)
        {
            node.getAndOperation().apply(this);
        }
        outAMissingOrExpr(node);
    }

    public void inAAndOperationAndOperation(AAndOperationAndOperation node)
    {
        defaultIn(node);
    }

    public void outAAndOperationAndOperation(AAndOperationAndOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndOperationAndOperation(AAndOperationAndOperation node)
    {
        inAAndOperationAndOperation(node);
        if(node.getEqualityOperation() != null)
        {
            node.getEqualityOperation().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getAndOperation() != null)
        {
            node.getAndOperation().apply(this);
        }
        outAAndOperationAndOperation(node);
    }

    public void inAGreaterLessEqualOperationAndOperation(AGreaterLessEqualOperationAndOperation node)
    {
        defaultIn(node);
    }

    public void outAGreaterLessEqualOperationAndOperation(AGreaterLessEqualOperationAndOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterLessEqualOperationAndOperation(AGreaterLessEqualOperationAndOperation node)
    {
        inAGreaterLessEqualOperationAndOperation(node);
        if(node.getEqualityOperation() != null)
        {
            node.getEqualityOperation().apply(this);
        }
        outAGreaterLessEqualOperationAndOperation(node);
    }

    public void inAEqualsComparisonEqualityOperation(AEqualsComparisonEqualityOperation node)
    {
        defaultIn(node);
    }

    public void outAEqualsComparisonEqualityOperation(AEqualsComparisonEqualityOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqualsComparisonEqualityOperation(AEqualsComparisonEqualityOperation node)
    {
        inAEqualsComparisonEqualityOperation(node);
        if(node.getGreaterLessEqualOperation() != null)
        {
            node.getGreaterLessEqualOperation().apply(this);
        }
        if(node.getEquals() != null)
        {
            node.getEquals().apply(this);
        }
        if(node.getEqualityOperation() != null)
        {
            node.getEqualityOperation().apply(this);
        }
        outAEqualsComparisonEqualityOperation(node);
    }

    public void inANotEqualsComparisonEqualityOperation(ANotEqualsComparisonEqualityOperation node)
    {
        defaultIn(node);
    }

    public void outANotEqualsComparisonEqualityOperation(ANotEqualsComparisonEqualityOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotEqualsComparisonEqualityOperation(ANotEqualsComparisonEqualityOperation node)
    {
        inANotEqualsComparisonEqualityOperation(node);
        if(node.getGreaterLessEqualOperation() != null)
        {
            node.getGreaterLessEqualOperation().apply(this);
        }
        if(node.getNotEquals() != null)
        {
            node.getNotEquals().apply(this);
        }
        if(node.getEqualityOperation() != null)
        {
            node.getEqualityOperation().apply(this);
        }
        outANotEqualsComparisonEqualityOperation(node);
    }

    public void inANoEqualityOperationEqualityOperation(ANoEqualityOperationEqualityOperation node)
    {
        defaultIn(node);
    }

    public void outANoEqualityOperationEqualityOperation(ANoEqualityOperationEqualityOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANoEqualityOperationEqualityOperation(ANoEqualityOperationEqualityOperation node)
    {
        inANoEqualityOperationEqualityOperation(node);
        if(node.getGreaterLessEqualOperation() != null)
        {
            node.getGreaterLessEqualOperation().apply(this);
        }
        outANoEqualityOperationEqualityOperation(node);
    }

    public void inALessThanGreaterLessEqualOperation(ALessThanGreaterLessEqualOperation node)
    {
        defaultIn(node);
    }

    public void outALessThanGreaterLessEqualOperation(ALessThanGreaterLessEqualOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessThanGreaterLessEqualOperation(ALessThanGreaterLessEqualOperation node)
    {
        inALessThanGreaterLessEqualOperation(node);
        if(node.getPlusMinusTarget() != null)
        {
            node.getPlusMinusTarget().apply(this);
        }
        if(node.getLessThan() != null)
        {
            node.getLessThan().apply(this);
        }
        if(node.getPlusMinusSrc() != null)
        {
            node.getPlusMinusSrc().apply(this);
        }
        outALessThanGreaterLessEqualOperation(node);
    }

    public void inAGreaterThanGreaterLessEqualOperation(AGreaterThanGreaterLessEqualOperation node)
    {
        defaultIn(node);
    }

    public void outAGreaterThanGreaterLessEqualOperation(AGreaterThanGreaterLessEqualOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterThanGreaterLessEqualOperation(AGreaterThanGreaterLessEqualOperation node)
    {
        inAGreaterThanGreaterLessEqualOperation(node);
        if(node.getPlusMinusTarget() != null)
        {
            node.getPlusMinusTarget().apply(this);
        }
        if(node.getGreaterThan() != null)
        {
            node.getGreaterThan().apply(this);
        }
        if(node.getPlusMinusSrc() != null)
        {
            node.getPlusMinusSrc().apply(this);
        }
        outAGreaterThanGreaterLessEqualOperation(node);
    }

    public void inALessThanOrEqGreaterLessEqualOperation(ALessThanOrEqGreaterLessEqualOperation node)
    {
        defaultIn(node);
    }

    public void outALessThanOrEqGreaterLessEqualOperation(ALessThanOrEqGreaterLessEqualOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALessThanOrEqGreaterLessEqualOperation(ALessThanOrEqGreaterLessEqualOperation node)
    {
        inALessThanOrEqGreaterLessEqualOperation(node);
        if(node.getPlusMinusTarget() != null)
        {
            node.getPlusMinusTarget().apply(this);
        }
        if(node.getLessThanOrEq() != null)
        {
            node.getLessThanOrEq().apply(this);
        }
        if(node.getPlusMinusSrc() != null)
        {
            node.getPlusMinusSrc().apply(this);
        }
        outALessThanOrEqGreaterLessEqualOperation(node);
    }

    public void inAGreaterThanOrEqGreaterLessEqualOperation(AGreaterThanOrEqGreaterLessEqualOperation node)
    {
        defaultIn(node);
    }

    public void outAGreaterThanOrEqGreaterLessEqualOperation(AGreaterThanOrEqGreaterLessEqualOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGreaterThanOrEqGreaterLessEqualOperation(AGreaterThanOrEqGreaterLessEqualOperation node)
    {
        inAGreaterThanOrEqGreaterLessEqualOperation(node);
        if(node.getPlusMinusTarget() != null)
        {
            node.getPlusMinusTarget().apply(this);
        }
        if(node.getGreaterThanOrEq() != null)
        {
            node.getGreaterThanOrEq().apply(this);
        }
        if(node.getPlusMinusSrc() != null)
        {
            node.getPlusMinusSrc().apply(this);
        }
        outAGreaterThanOrEqGreaterLessEqualOperation(node);
    }

    public void inAPlusMinusExprGreaterLessEqualOperation(APlusMinusExprGreaterLessEqualOperation node)
    {
        defaultIn(node);
    }

    public void outAPlusMinusExprGreaterLessEqualOperation(APlusMinusExprGreaterLessEqualOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusMinusExprGreaterLessEqualOperation(APlusMinusExprGreaterLessEqualOperation node)
    {
        inAPlusMinusExprGreaterLessEqualOperation(node);
        if(node.getPlusMinusExpr() != null)
        {
            node.getPlusMinusExpr().apply(this);
        }
        outAPlusMinusExprGreaterLessEqualOperation(node);
    }

    public void inAAdditionPlusMinusExpr(AAdditionPlusMinusExpr node)
    {
        defaultIn(node);
    }

    public void outAAdditionPlusMinusExpr(AAdditionPlusMinusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAdditionPlusMinusExpr(AAdditionPlusMinusExpr node)
    {
        inAAdditionPlusMinusExpr(node);
        if(node.getMultDivModTarget() != null)
        {
            node.getMultDivModTarget().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        if(node.getPlusMinusExprSrc() != null)
        {
            node.getPlusMinusExprSrc().apply(this);
        }
        outAAdditionPlusMinusExpr(node);
    }

    public void inASubtractionPlusMinusExpr(ASubtractionPlusMinusExpr node)
    {
        defaultIn(node);
    }

    public void outASubtractionPlusMinusExpr(ASubtractionPlusMinusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtractionPlusMinusExpr(ASubtractionPlusMinusExpr node)
    {
        inASubtractionPlusMinusExpr(node);
        if(node.getMultDivModTarget() != null)
        {
            node.getMultDivModTarget().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        if(node.getPlusMinusExprSrc() != null)
        {
            node.getPlusMinusExprSrc().apply(this);
        }
        outASubtractionPlusMinusExpr(node);
    }

    public void inAMultDivModExprPlusMinusExpr(AMultDivModExprPlusMinusExpr node)
    {
        defaultIn(node);
    }

    public void outAMultDivModExprPlusMinusExpr(AMultDivModExprPlusMinusExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultDivModExprPlusMinusExpr(AMultDivModExprPlusMinusExpr node)
    {
        inAMultDivModExprPlusMinusExpr(node);
        if(node.getMultDivModExpr() != null)
        {
            node.getMultDivModExpr().apply(this);
        }
        outAMultDivModExprPlusMinusExpr(node);
    }

    public void inAMultiplicationMultDivModExpr(AMultiplicationMultDivModExpr node)
    {
        defaultIn(node);
    }

    public void outAMultiplicationMultDivModExpr(AMultiplicationMultDivModExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplicationMultDivModExpr(AMultiplicationMultDivModExpr node)
    {
        inAMultiplicationMultDivModExpr(node);
        if(node.getUnitaryTarget() != null)
        {
            node.getUnitaryTarget().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getMultDivModExprSrc() != null)
        {
            node.getMultDivModExprSrc().apply(this);
        }
        outAMultiplicationMultDivModExpr(node);
    }

    public void inADivisionMultDivModExpr(ADivisionMultDivModExpr node)
    {
        defaultIn(node);
    }

    public void outADivisionMultDivModExpr(ADivisionMultDivModExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisionMultDivModExpr(ADivisionMultDivModExpr node)
    {
        inADivisionMultDivModExpr(node);
        if(node.getUnitaryTarget() != null)
        {
            node.getUnitaryTarget().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getMultDivModExprSrc() != null)
        {
            node.getMultDivModExprSrc().apply(this);
        }
        outADivisionMultDivModExpr(node);
    }

    public void inAModuloMultDivModExpr(AModuloMultDivModExpr node)
    {
        defaultIn(node);
    }

    public void outAModuloMultDivModExpr(AModuloMultDivModExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModuloMultDivModExpr(AModuloMultDivModExpr node)
    {
        inAModuloMultDivModExpr(node);
        if(node.getUnitaryTarget() != null)
        {
            node.getUnitaryTarget().apply(this);
        }
        if(node.getModulo() != null)
        {
            node.getModulo().apply(this);
        }
        if(node.getMultDivModExprSrc() != null)
        {
            node.getMultDivModExprSrc().apply(this);
        }
        outAModuloMultDivModExpr(node);
    }

    public void inAUnitaryExprMultDivModExpr(AUnitaryExprMultDivModExpr node)
    {
        defaultIn(node);
    }

    public void outAUnitaryExprMultDivModExpr(AUnitaryExprMultDivModExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnitaryExprMultDivModExpr(AUnitaryExprMultDivModExpr node)
    {
        inAUnitaryExprMultDivModExpr(node);
        if(node.getUnitaryExpr() != null)
        {
            node.getUnitaryExpr().apply(this);
        }
        outAUnitaryExprMultDivModExpr(node);
    }

    public void inAUnaryNotUnitaryExpr(AUnaryNotUnitaryExpr node)
    {
        defaultIn(node);
    }

    public void outAUnaryNotUnitaryExpr(AUnaryNotUnitaryExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnaryNotUnitaryExpr(AUnaryNotUnitaryExpr node)
    {
        inAUnaryNotUnitaryExpr(node);
        if(node.getUnitaryExpr() != null)
        {
            node.getUnitaryExpr().apply(this);
        }
        if(node.getNot() != null)
        {
            node.getNot().apply(this);
        }
        outAUnaryNotUnitaryExpr(node);
    }

    public void inAUnaryPlusUnitaryExpr(AUnaryPlusUnitaryExpr node)
    {
        defaultIn(node);
    }

    public void outAUnaryPlusUnitaryExpr(AUnaryPlusUnitaryExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnaryPlusUnitaryExpr(AUnaryPlusUnitaryExpr node)
    {
        inAUnaryPlusUnitaryExpr(node);
        if(node.getUnitaryExpr() != null)
        {
            node.getUnitaryExpr().apply(this);
        }
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        outAUnaryPlusUnitaryExpr(node);
    }

    public void inAUnaryMinusUnitaryExpr(AUnaryMinusUnitaryExpr node)
    {
        defaultIn(node);
    }

    public void outAUnaryMinusUnitaryExpr(AUnaryMinusUnitaryExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnaryMinusUnitaryExpr(AUnaryMinusUnitaryExpr node)
    {
        inAUnaryMinusUnitaryExpr(node);
        if(node.getUnitaryExpr() != null)
        {
            node.getUnitaryExpr().apply(this);
        }
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outAUnaryMinusUnitaryExpr(node);
    }

    public void inAPrimaryUnitaryExpr(APrimaryUnitaryExpr node)
    {
        defaultIn(node);
    }

    public void outAPrimaryUnitaryExpr(APrimaryUnitaryExpr node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryUnitaryExpr(APrimaryUnitaryExpr node)
    {
        inAPrimaryUnitaryExpr(node);
        if(node.getPrimary() != null)
        {
            node.getPrimary().apply(this);
        }
        outAPrimaryUnitaryExpr(node);
    }

    public void inAPrimaryFieldPrimary(APrimaryFieldPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryFieldPrimary(APrimaryFieldPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryFieldPrimary(APrimaryFieldPrimary node)
    {
        inAPrimaryFieldPrimary(node);
        if(node.getFieldAccess() != null)
        {
            node.getFieldAccess().apply(this);
        }
        outAPrimaryFieldPrimary(node);
    }

    public void inAPrimaryMethodCallPrimary(APrimaryMethodCallPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryMethodCallPrimary(APrimaryMethodCallPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryMethodCallPrimary(APrimaryMethodCallPrimary node)
    {
        inAPrimaryMethodCallPrimary(node);
        if(node.getMethodCall() != null)
        {
            node.getMethodCall().apply(this);
        }
        outAPrimaryMethodCallPrimary(node);
    }

    public void inAPrimaryIntegerLiteralPrimary(APrimaryIntegerLiteralPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryIntegerLiteralPrimary(APrimaryIntegerLiteralPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryIntegerLiteralPrimary(APrimaryIntegerLiteralPrimary node)
    {
        inAPrimaryIntegerLiteralPrimary(node);
        if(node.getIntegerLiteral() != null)
        {
            node.getIntegerLiteral().apply(this);
        }
        outAPrimaryIntegerLiteralPrimary(node);
    }

    public void inAPrimaryCharLiteralPrimary(APrimaryCharLiteralPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryCharLiteralPrimary(APrimaryCharLiteralPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryCharLiteralPrimary(APrimaryCharLiteralPrimary node)
    {
        inAPrimaryCharLiteralPrimary(node);
        if(node.getCharLiteral() != null)
        {
            node.getCharLiteral().apply(this);
        }
        outAPrimaryCharLiteralPrimary(node);
    }

    public void inAPrimaryStringLiteralPrimary(APrimaryStringLiteralPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryStringLiteralPrimary(APrimaryStringLiteralPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryStringLiteralPrimary(APrimaryStringLiteralPrimary node)
    {
        inAPrimaryStringLiteralPrimary(node);
        if(node.getStringLiteral() != null)
        {
            node.getStringLiteral().apply(this);
        }
        outAPrimaryStringLiteralPrimary(node);
    }

    public void inAPrimaryFloatLiteralPrimary(APrimaryFloatLiteralPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryFloatLiteralPrimary(APrimaryFloatLiteralPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryFloatLiteralPrimary(APrimaryFloatLiteralPrimary node)
    {
        inAPrimaryFloatLiteralPrimary(node);
        if(node.getFloatLit() != null)
        {
            node.getFloatLit().apply(this);
        }
        outAPrimaryFloatLiteralPrimary(node);
    }

    public void inAPrimaryTruePrimary(APrimaryTruePrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryTruePrimary(APrimaryTruePrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryTruePrimary(APrimaryTruePrimary node)
    {
        inAPrimaryTruePrimary(node);
        if(node.getTrue() != null)
        {
            node.getTrue().apply(this);
        }
        outAPrimaryTruePrimary(node);
    }

    public void inAPrimaryFalsePrimary(APrimaryFalsePrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryFalsePrimary(APrimaryFalsePrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryFalsePrimary(APrimaryFalsePrimary node)
    {
        inAPrimaryFalsePrimary(node);
        if(node.getFalse() != null)
        {
            node.getFalse().apply(this);
        }
        outAPrimaryFalsePrimary(node);
    }

    public void inAPrimaryExprPrimary(APrimaryExprPrimary node)
    {
        defaultIn(node);
    }

    public void outAPrimaryExprPrimary(APrimaryExprPrimary node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimaryExprPrimary(APrimaryExprPrimary node)
    {
        inAPrimaryExprPrimary(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpr() != null)
        {
            node.getExpr().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAPrimaryExprPrimary(node);
    }

    public void inAIntegerLiteralIntegerParamOrValue(AIntegerLiteralIntegerParamOrValue node)
    {
        defaultIn(node);
    }

    public void outAIntegerLiteralIntegerParamOrValue(AIntegerLiteralIntegerParamOrValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntegerLiteralIntegerParamOrValue(AIntegerLiteralIntegerParamOrValue node)
    {
        inAIntegerLiteralIntegerParamOrValue(node);
        if(node.getIntegerLiteral() != null)
        {
            node.getIntegerLiteral().apply(this);
        }
        outAIntegerLiteralIntegerParamOrValue(node);
    }

    public void inAIdentifierIntegerParamOrValue(AIdentifierIntegerParamOrValue node)
    {
        defaultIn(node);
    }

    public void outAIdentifierIntegerParamOrValue(AIdentifierIntegerParamOrValue node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentifierIntegerParamOrValue(AIdentifierIntegerParamOrValue node)
    {
        inAIdentifierIntegerParamOrValue(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAIdentifierIntegerParamOrValue(node);
    }
}
