/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAm1M extends PM
{
    private TIf _if_;
    private PCondition _condition_;
    private PM _m1_;
    private TElse _else_;
    private PM _m2_;

    public AAm1M()
    {
        // Constructor
    }

    public AAm1M(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") PM _m1_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PM _m2_)
    {
        // Constructor
        setIf(_if_);

        setCondition(_condition_);

        setM1(_m1_);

        setElse(_else_);

        setM2(_m2_);

    }

    @Override
    public Object clone()
    {
        return new AAm1M(
            cloneNode(this._if_),
            cloneNode(this._condition_),
            cloneNode(this._m1_),
            cloneNode(this._else_),
            cloneNode(this._m2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAm1M(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PM getM1()
    {
        return this._m1_;
    }

    public void setM1(PM node)
    {
        if(this._m1_ != null)
        {
            this._m1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._m1_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PM getM2()
    {
        return this._m2_;
    }

    public void setM2(PM node)
    {
        if(this._m2_ != null)
        {
            this._m2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._m2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._condition_)
            + toString(this._m1_)
            + toString(this._else_)
            + toString(this._m2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._m1_ == child)
        {
            this._m1_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._m2_ == child)
        {
            this._m2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._m1_ == oldChild)
        {
            setM1((PM) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._m2_ == oldChild)
        {
            setM2((PM) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
