/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAm2M extends PM
{
    private POther _other_;

    public AAm2M()
    {
        // Constructor
    }

    public AAm2M(
        @SuppressWarnings("hiding") POther _other_)
    {
        // Constructor
        setOther(_other_);

    }

    @Override
    public Object clone()
    {
        return new AAm2M(
            cloneNode(this._other_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAm2M(this);
    }

    public POther getOther()
    {
        return this._other_;
    }

    public void setOther(POther node)
    {
        if(this._other_ != null)
        {
            this._other_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._other_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._other_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._other_ == child)
        {
            this._other_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._other_ == oldChild)
        {
            setOther((POther) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
