/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAndOperationAndOperation extends PAndOperation
{
    private PAndOperation _andOperation_;
    private TAnd _and_;
    private PEqualityOperation _equalityOperation_;

    public AAndOperationAndOperation()
    {
        // Constructor
    }

    public AAndOperationAndOperation(
        @SuppressWarnings("hiding") PAndOperation _andOperation_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PEqualityOperation _equalityOperation_)
    {
        // Constructor
        setAndOperation(_andOperation_);

        setAnd(_and_);

        setEqualityOperation(_equalityOperation_);

    }

    @Override
    public Object clone()
    {
        return new AAndOperationAndOperation(
            cloneNode(this._andOperation_),
            cloneNode(this._and_),
            cloneNode(this._equalityOperation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndOperationAndOperation(this);
    }

    public PAndOperation getAndOperation()
    {
        return this._andOperation_;
    }

    public void setAndOperation(PAndOperation node)
    {
        if(this._andOperation_ != null)
        {
            this._andOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andOperation_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PEqualityOperation getEqualityOperation()
    {
        return this._equalityOperation_;
    }

    public void setEqualityOperation(PEqualityOperation node)
    {
        if(this._equalityOperation_ != null)
        {
            this._equalityOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andOperation_)
            + toString(this._and_)
            + toString(this._equalityOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andOperation_ == child)
        {
            this._andOperation_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._equalityOperation_ == child)
        {
            this._equalityOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andOperation_ == oldChild)
        {
            setAndOperation((PAndOperation) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._equalityOperation_ == oldChild)
        {
            setEqualityOperation((PEqualityOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
