/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AArrayDotRefArrayRef extends PArrayRef
{
    private TIdentifier _mainIdentifier_;
    private TDot _dot_;
    private TIdentifier _subIdentifier_;
    private TLBkt _lBkt_;
    private TIntegerLiteral _integerLiteral_;
    private TRBkt _rBkt_;

    public AArrayDotRefArrayRef()
    {
        // Constructor
    }

    public AArrayDotRefArrayRef(
        @SuppressWarnings("hiding") TIdentifier _mainIdentifier_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TIdentifier _subIdentifier_,
        @SuppressWarnings("hiding") TLBkt _lBkt_,
        @SuppressWarnings("hiding") TIntegerLiteral _integerLiteral_,
        @SuppressWarnings("hiding") TRBkt _rBkt_)
    {
        // Constructor
        setMainIdentifier(_mainIdentifier_);

        setDot(_dot_);

        setSubIdentifier(_subIdentifier_);

        setLBkt(_lBkt_);

        setIntegerLiteral(_integerLiteral_);

        setRBkt(_rBkt_);

    }

    @Override
    public Object clone()
    {
        return new AArrayDotRefArrayRef(
            cloneNode(this._mainIdentifier_),
            cloneNode(this._dot_),
            cloneNode(this._subIdentifier_),
            cloneNode(this._lBkt_),
            cloneNode(this._integerLiteral_),
            cloneNode(this._rBkt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayDotRefArrayRef(this);
    }

    public TIdentifier getMainIdentifier()
    {
        return this._mainIdentifier_;
    }

    public void setMainIdentifier(TIdentifier node)
    {
        if(this._mainIdentifier_ != null)
        {
            this._mainIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mainIdentifier_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TIdentifier getSubIdentifier()
    {
        return this._subIdentifier_;
    }

    public void setSubIdentifier(TIdentifier node)
    {
        if(this._subIdentifier_ != null)
        {
            this._subIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subIdentifier_ = node;
    }

    public TLBkt getLBkt()
    {
        return this._lBkt_;
    }

    public void setLBkt(TLBkt node)
    {
        if(this._lBkt_ != null)
        {
            this._lBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBkt_ = node;
    }

    public TIntegerLiteral getIntegerLiteral()
    {
        return this._integerLiteral_;
    }

    public void setIntegerLiteral(TIntegerLiteral node)
    {
        if(this._integerLiteral_ != null)
        {
            this._integerLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._integerLiteral_ = node;
    }

    public TRBkt getRBkt()
    {
        return this._rBkt_;
    }

    public void setRBkt(TRBkt node)
    {
        if(this._rBkt_ != null)
        {
            this._rBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mainIdentifier_)
            + toString(this._dot_)
            + toString(this._subIdentifier_)
            + toString(this._lBkt_)
            + toString(this._integerLiteral_)
            + toString(this._rBkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mainIdentifier_ == child)
        {
            this._mainIdentifier_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._subIdentifier_ == child)
        {
            this._subIdentifier_ = null;
            return;
        }

        if(this._lBkt_ == child)
        {
            this._lBkt_ = null;
            return;
        }

        if(this._integerLiteral_ == child)
        {
            this._integerLiteral_ = null;
            return;
        }

        if(this._rBkt_ == child)
        {
            this._rBkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mainIdentifier_ == oldChild)
        {
            setMainIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._subIdentifier_ == oldChild)
        {
            setSubIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._lBkt_ == oldChild)
        {
            setLBkt((TLBkt) newChild);
            return;
        }

        if(this._integerLiteral_ == oldChild)
        {
            setIntegerLiteral((TIntegerLiteral) newChild);
            return;
        }

        if(this._rBkt_ == oldChild)
        {
            setRBkt((TRBkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
