/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAs1S extends PS
{
    private PM _m_;

    public AAs1S()
    {
        // Constructor
    }

    public AAs1S(
        @SuppressWarnings("hiding") PM _m_)
    {
        // Constructor
        setM(_m_);

    }

    @Override
    public Object clone()
    {
        return new AAs1S(
            cloneNode(this._m_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAs1S(this);
    }

    public PM getM()
    {
        return this._m_;
    }

    public void setM(PM node)
    {
        if(this._m_ != null)
        {
            this._m_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._m_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._m_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._m_ == child)
        {
            this._m_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._m_ == oldChild)
        {
            setM((PM) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
