/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAu2U extends PU
{
    private TIf _if_;
    private PCondition _condition_;
    private PM _u1_;
    private TElse _else_;
    private PU _u2_;

    public AAu2U()
    {
        // Constructor
    }

    public AAu2U(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCondition _condition_,
        @SuppressWarnings("hiding") PM _u1_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") PU _u2_)
    {
        // Constructor
        setIf(_if_);

        setCondition(_condition_);

        setU1(_u1_);

        setElse(_else_);

        setU2(_u2_);

    }

    @Override
    public Object clone()
    {
        return new AAu2U(
            cloneNode(this._if_),
            cloneNode(this._condition_),
            cloneNode(this._u1_),
            cloneNode(this._else_),
            cloneNode(this._u2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAu2U(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCondition getCondition()
    {
        return this._condition_;
    }

    public void setCondition(PCondition node)
    {
        if(this._condition_ != null)
        {
            this._condition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condition_ = node;
    }

    public PM getU1()
    {
        return this._u1_;
    }

    public void setU1(PM node)
    {
        if(this._u1_ != null)
        {
            this._u1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._u1_ = node;
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public PU getU2()
    {
        return this._u2_;
    }

    public void setU2(PU node)
    {
        if(this._u2_ != null)
        {
            this._u2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._u2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._condition_)
            + toString(this._u1_)
            + toString(this._else_)
            + toString(this._u2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._condition_ == child)
        {
            this._condition_ = null;
            return;
        }

        if(this._u1_ == child)
        {
            this._u1_ = null;
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._u2_ == child)
        {
            this._u2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._condition_ == oldChild)
        {
            setCondition((PCondition) newChild);
            return;
        }

        if(this._u1_ == oldChild)
        {
            setU1((PM) newChild);
            return;
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        if(this._u2_ == oldChild)
        {
            setU2((PU) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
