/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AEqualsComparisonEqualityOperation extends PEqualityOperation
{
    private PEqualityOperation _equalityOperation_;
    private TEquals _equals_;
    private PGreaterLessEqualOperation _greaterLessEqualOperation_;

    public AEqualsComparisonEqualityOperation()
    {
        // Constructor
    }

    public AEqualsComparisonEqualityOperation(
        @SuppressWarnings("hiding") PEqualityOperation _equalityOperation_,
        @SuppressWarnings("hiding") TEquals _equals_,
        @SuppressWarnings("hiding") PGreaterLessEqualOperation _greaterLessEqualOperation_)
    {
        // Constructor
        setEqualityOperation(_equalityOperation_);

        setEquals(_equals_);

        setGreaterLessEqualOperation(_greaterLessEqualOperation_);

    }

    @Override
    public Object clone()
    {
        return new AEqualsComparisonEqualityOperation(
            cloneNode(this._equalityOperation_),
            cloneNode(this._equals_),
            cloneNode(this._greaterLessEqualOperation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualsComparisonEqualityOperation(this);
    }

    public PEqualityOperation getEqualityOperation()
    {
        return this._equalityOperation_;
    }

    public void setEqualityOperation(PEqualityOperation node)
    {
        if(this._equalityOperation_ != null)
        {
            this._equalityOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityOperation_ = node;
    }

    public TEquals getEquals()
    {
        return this._equals_;
    }

    public void setEquals(TEquals node)
    {
        if(this._equals_ != null)
        {
            this._equals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equals_ = node;
    }

    public PGreaterLessEqualOperation getGreaterLessEqualOperation()
    {
        return this._greaterLessEqualOperation_;
    }

    public void setGreaterLessEqualOperation(PGreaterLessEqualOperation node)
    {
        if(this._greaterLessEqualOperation_ != null)
        {
            this._greaterLessEqualOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterLessEqualOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityOperation_)
            + toString(this._equals_)
            + toString(this._greaterLessEqualOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityOperation_ == child)
        {
            this._equalityOperation_ = null;
            return;
        }

        if(this._equals_ == child)
        {
            this._equals_ = null;
            return;
        }

        if(this._greaterLessEqualOperation_ == child)
        {
            this._greaterLessEqualOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityOperation_ == oldChild)
        {
            setEqualityOperation((PEqualityOperation) newChild);
            return;
        }

        if(this._equals_ == oldChild)
        {
            setEquals((TEquals) newChild);
            return;
        }

        if(this._greaterLessEqualOperation_ == oldChild)
        {
            setGreaterLessEqualOperation((PGreaterLessEqualOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
