/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AGreaterLessEqualOperationAndOperation extends PAndOperation
{
    private PEqualityOperation _equalityOperation_;

    public AGreaterLessEqualOperationAndOperation()
    {
        // Constructor
    }

    public AGreaterLessEqualOperationAndOperation(
        @SuppressWarnings("hiding") PEqualityOperation _equalityOperation_)
    {
        // Constructor
        setEqualityOperation(_equalityOperation_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterLessEqualOperationAndOperation(
            cloneNode(this._equalityOperation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterLessEqualOperationAndOperation(this);
    }

    public PEqualityOperation getEqualityOperation()
    {
        return this._equalityOperation_;
    }

    public void setEqualityOperation(PEqualityOperation node)
    {
        if(this._equalityOperation_ != null)
        {
            this._equalityOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityOperation_ == child)
        {
            this._equalityOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityOperation_ == oldChild)
        {
            setEqualityOperation((PEqualityOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
