/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AGreaterThanOrEqGreaterLessEqualOperation extends PGreaterLessEqualOperation
{
    private PPlusMinusExpr _plusMinusSrc_;
    private TGreaterThanOrEq _greaterThanOrEq_;
    private PPlusMinusExpr _plusMinusTarget_;

    public AGreaterThanOrEqGreaterLessEqualOperation()
    {
        // Constructor
    }

    public AGreaterThanOrEqGreaterLessEqualOperation(
        @SuppressWarnings("hiding") PPlusMinusExpr _plusMinusSrc_,
        @SuppressWarnings("hiding") TGreaterThanOrEq _greaterThanOrEq_,
        @SuppressWarnings("hiding") PPlusMinusExpr _plusMinusTarget_)
    {
        // Constructor
        setPlusMinusSrc(_plusMinusSrc_);

        setGreaterThanOrEq(_greaterThanOrEq_);

        setPlusMinusTarget(_plusMinusTarget_);

    }

    @Override
    public Object clone()
    {
        return new AGreaterThanOrEqGreaterLessEqualOperation(
            cloneNode(this._plusMinusSrc_),
            cloneNode(this._greaterThanOrEq_),
            cloneNode(this._plusMinusTarget_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGreaterThanOrEqGreaterLessEqualOperation(this);
    }

    public PPlusMinusExpr getPlusMinusSrc()
    {
        return this._plusMinusSrc_;
    }

    public void setPlusMinusSrc(PPlusMinusExpr node)
    {
        if(this._plusMinusSrc_ != null)
        {
            this._plusMinusSrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusSrc_ = node;
    }

    public TGreaterThanOrEq getGreaterThanOrEq()
    {
        return this._greaterThanOrEq_;
    }

    public void setGreaterThanOrEq(TGreaterThanOrEq node)
    {
        if(this._greaterThanOrEq_ != null)
        {
            this._greaterThanOrEq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterThanOrEq_ = node;
    }

    public PPlusMinusExpr getPlusMinusTarget()
    {
        return this._plusMinusTarget_;
    }

    public void setPlusMinusTarget(PPlusMinusExpr node)
    {
        if(this._plusMinusTarget_ != null)
        {
            this._plusMinusTarget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusTarget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusMinusSrc_)
            + toString(this._greaterThanOrEq_)
            + toString(this._plusMinusTarget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusMinusSrc_ == child)
        {
            this._plusMinusSrc_ = null;
            return;
        }

        if(this._greaterThanOrEq_ == child)
        {
            this._greaterThanOrEq_ = null;
            return;
        }

        if(this._plusMinusTarget_ == child)
        {
            this._plusMinusTarget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusMinusSrc_ == oldChild)
        {
            setPlusMinusSrc((PPlusMinusExpr) newChild);
            return;
        }

        if(this._greaterThanOrEq_ == oldChild)
        {
            setGreaterThanOrEq((TGreaterThanOrEq) newChild);
            return;
        }

        if(this._plusMinusTarget_ == oldChild)
        {
            setPlusMinusTarget((PPlusMinusExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
