/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultMemberDeclMemberDecls extends PMemberDecls
{
    private PMemberDecls _memberDecls_;
    private PMemberDecl _memberDecl_;

    public AMultMemberDeclMemberDecls()
    {
        // Constructor
    }

    public AMultMemberDeclMemberDecls(
        @SuppressWarnings("hiding") PMemberDecls _memberDecls_,
        @SuppressWarnings("hiding") PMemberDecl _memberDecl_)
    {
        // Constructor
        setMemberDecls(_memberDecls_);

        setMemberDecl(_memberDecl_);

    }

    @Override
    public Object clone()
    {
        return new AMultMemberDeclMemberDecls(
            cloneNode(this._memberDecls_),
            cloneNode(this._memberDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultMemberDeclMemberDecls(this);
    }

    public PMemberDecls getMemberDecls()
    {
        return this._memberDecls_;
    }

    public void setMemberDecls(PMemberDecls node)
    {
        if(this._memberDecls_ != null)
        {
            this._memberDecls_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._memberDecls_ = node;
    }

    public PMemberDecl getMemberDecl()
    {
        return this._memberDecl_;
    }

    public void setMemberDecl(PMemberDecl node)
    {
        if(this._memberDecl_ != null)
        {
            this._memberDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._memberDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._memberDecls_)
            + toString(this._memberDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._memberDecls_ == child)
        {
            this._memberDecls_ = null;
            return;
        }

        if(this._memberDecl_ == child)
        {
            this._memberDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._memberDecls_ == oldChild)
        {
            setMemberDecls((PMemberDecls) newChild);
            return;
        }

        if(this._memberDecl_ == oldChild)
        {
            setMemberDecl((PMemberDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
