/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultDivModExprPlusMinusExpr extends PPlusMinusExpr
{
    private PMultDivModExpr _multDivModExpr_;

    public AMultDivModExprPlusMinusExpr()
    {
        // Constructor
    }

    public AMultDivModExprPlusMinusExpr(
        @SuppressWarnings("hiding") PMultDivModExpr _multDivModExpr_)
    {
        // Constructor
        setMultDivModExpr(_multDivModExpr_);

    }

    @Override
    public Object clone()
    {
        return new AMultDivModExprPlusMinusExpr(
            cloneNode(this._multDivModExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultDivModExprPlusMinusExpr(this);
    }

    public PMultDivModExpr getMultDivModExpr()
    {
        return this._multDivModExpr_;
    }

    public void setMultDivModExpr(PMultDivModExpr node)
    {
        if(this._multDivModExpr_ != null)
        {
            this._multDivModExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDivModExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multDivModExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multDivModExpr_ == child)
        {
            this._multDivModExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multDivModExpr_ == oldChild)
        {
            setMultDivModExpr((PMultDivModExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
