/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicationMultDivModExpr extends PMultDivModExpr
{
    private PMultDivModExpr _multDivModExprSrc_;
    private TMult _mult_;
    private PUnitaryExpr _unitaryTarget_;

    public AMultiplicationMultDivModExpr()
    {
        // Constructor
    }

    public AMultiplicationMultDivModExpr(
        @SuppressWarnings("hiding") PMultDivModExpr _multDivModExprSrc_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PUnitaryExpr _unitaryTarget_)
    {
        // Constructor
        setMultDivModExprSrc(_multDivModExprSrc_);

        setMult(_mult_);

        setUnitaryTarget(_unitaryTarget_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicationMultDivModExpr(
            cloneNode(this._multDivModExprSrc_),
            cloneNode(this._mult_),
            cloneNode(this._unitaryTarget_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicationMultDivModExpr(this);
    }

    public PMultDivModExpr getMultDivModExprSrc()
    {
        return this._multDivModExprSrc_;
    }

    public void setMultDivModExprSrc(PMultDivModExpr node)
    {
        if(this._multDivModExprSrc_ != null)
        {
            this._multDivModExprSrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDivModExprSrc_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PUnitaryExpr getUnitaryTarget()
    {
        return this._unitaryTarget_;
    }

    public void setUnitaryTarget(PUnitaryExpr node)
    {
        if(this._unitaryTarget_ != null)
        {
            this._unitaryTarget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unitaryTarget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multDivModExprSrc_)
            + toString(this._mult_)
            + toString(this._unitaryTarget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multDivModExprSrc_ == child)
        {
            this._multDivModExprSrc_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._unitaryTarget_ == child)
        {
            this._unitaryTarget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multDivModExprSrc_ == oldChild)
        {
            setMultDivModExprSrc((PMultDivModExpr) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._unitaryTarget_ == oldChild)
        {
            setUnitaryTarget((PUnitaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
