/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultStmtStmts extends PStmts
{
    private PStmts _stmts_;
    private PS _s_;

    public AMultStmtStmts()
    {
        // Constructor
    }

    public AMultStmtStmts(
        @SuppressWarnings("hiding") PStmts _stmts_,
        @SuppressWarnings("hiding") PS _s_)
    {
        // Constructor
        setStmts(_stmts_);

        setS(_s_);

    }

    @Override
    public Object clone()
    {
        return new AMultStmtStmts(
            cloneNode(this._stmts_),
            cloneNode(this._s_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultStmtStmts(this);
    }

    public PStmts getStmts()
    {
        return this._stmts_;
    }

    public void setStmts(PStmts node)
    {
        if(this._stmts_ != null)
        {
            this._stmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stmts_ = node;
    }

    public PS getS()
    {
        return this._s_;
    }

    public void setS(PS node)
    {
        if(this._s_ != null)
        {
            this._s_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stmts_)
            + toString(this._s_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stmts_ == child)
        {
            this._stmts_ = null;
            return;
        }

        if(this._s_ == child)
        {
            this._s_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stmts_ == oldChild)
        {
            setStmts((PStmts) newChild);
            return;
        }

        if(this._s_ == oldChild)
        {
            setS((PS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
