/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANoEqualityOperationEqualityOperation extends PEqualityOperation
{
    private PGreaterLessEqualOperation _greaterLessEqualOperation_;

    public ANoEqualityOperationEqualityOperation()
    {
        // Constructor
    }

    public ANoEqualityOperationEqualityOperation(
        @SuppressWarnings("hiding") PGreaterLessEqualOperation _greaterLessEqualOperation_)
    {
        // Constructor
        setGreaterLessEqualOperation(_greaterLessEqualOperation_);

    }

    @Override
    public Object clone()
    {
        return new ANoEqualityOperationEqualityOperation(
            cloneNode(this._greaterLessEqualOperation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoEqualityOperationEqualityOperation(this);
    }

    public PGreaterLessEqualOperation getGreaterLessEqualOperation()
    {
        return this._greaterLessEqualOperation_;
    }

    public void setGreaterLessEqualOperation(PGreaterLessEqualOperation node)
    {
        if(this._greaterLessEqualOperation_ != null)
        {
            this._greaterLessEqualOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterLessEqualOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._greaterLessEqualOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._greaterLessEqualOperation_ == child)
        {
            this._greaterLessEqualOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._greaterLessEqualOperation_ == oldChild)
        {
            setGreaterLessEqualOperation((PGreaterLessEqualOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
