/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotEqualsComparisonEqualityOperation extends PEqualityOperation
{
    private PEqualityOperation _equalityOperation_;
    private TNotEquals _notEquals_;
    private PGreaterLessEqualOperation _greaterLessEqualOperation_;

    public ANotEqualsComparisonEqualityOperation()
    {
        // Constructor
    }

    public ANotEqualsComparisonEqualityOperation(
        @SuppressWarnings("hiding") PEqualityOperation _equalityOperation_,
        @SuppressWarnings("hiding") TNotEquals _notEquals_,
        @SuppressWarnings("hiding") PGreaterLessEqualOperation _greaterLessEqualOperation_)
    {
        // Constructor
        setEqualityOperation(_equalityOperation_);

        setNotEquals(_notEquals_);

        setGreaterLessEqualOperation(_greaterLessEqualOperation_);

    }

    @Override
    public Object clone()
    {
        return new ANotEqualsComparisonEqualityOperation(
            cloneNode(this._equalityOperation_),
            cloneNode(this._notEquals_),
            cloneNode(this._greaterLessEqualOperation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotEqualsComparisonEqualityOperation(this);
    }

    public PEqualityOperation getEqualityOperation()
    {
        return this._equalityOperation_;
    }

    public void setEqualityOperation(PEqualityOperation node)
    {
        if(this._equalityOperation_ != null)
        {
            this._equalityOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityOperation_ = node;
    }

    public TNotEquals getNotEquals()
    {
        return this._notEquals_;
    }

    public void setNotEquals(TNotEquals node)
    {
        if(this._notEquals_ != null)
        {
            this._notEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notEquals_ = node;
    }

    public PGreaterLessEqualOperation getGreaterLessEqualOperation()
    {
        return this._greaterLessEqualOperation_;
    }

    public void setGreaterLessEqualOperation(PGreaterLessEqualOperation node)
    {
        if(this._greaterLessEqualOperation_ != null)
        {
            this._greaterLessEqualOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._greaterLessEqualOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityOperation_)
            + toString(this._notEquals_)
            + toString(this._greaterLessEqualOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityOperation_ == child)
        {
            this._equalityOperation_ = null;
            return;
        }

        if(this._notEquals_ == child)
        {
            this._notEquals_ = null;
            return;
        }

        if(this._greaterLessEqualOperation_ == child)
        {
            this._greaterLessEqualOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityOperation_ == oldChild)
        {
            setEqualityOperation((PEqualityOperation) newChild);
            return;
        }

        if(this._notEquals_ == oldChild)
        {
            setNotEquals((TNotEquals) newChild);
            return;
        }

        if(this._greaterLessEqualOperation_ == oldChild)
        {
            setGreaterLessEqualOperation((PGreaterLessEqualOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
