/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotEqualsLogicalExpr extends PLogicalExpr
{
    private PPlusMinusExpr _plusMinusSrc_;
    private TNotEquals _notEquals_;
    private PPlusMinusExpr _plusMinusTarget_;

    public ANotEqualsLogicalExpr()
    {
        // Constructor
    }

    public ANotEqualsLogicalExpr(
        @SuppressWarnings("hiding") PPlusMinusExpr _plusMinusSrc_,
        @SuppressWarnings("hiding") TNotEquals _notEquals_,
        @SuppressWarnings("hiding") PPlusMinusExpr _plusMinusTarget_)
    {
        // Constructor
        setPlusMinusSrc(_plusMinusSrc_);

        setNotEquals(_notEquals_);

        setPlusMinusTarget(_plusMinusTarget_);

    }

    @Override
    public Object clone()
    {
        return new ANotEqualsLogicalExpr(
            cloneNode(this._plusMinusSrc_),
            cloneNode(this._notEquals_),
            cloneNode(this._plusMinusTarget_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotEqualsLogicalExpr(this);
    }

    public PPlusMinusExpr getPlusMinusSrc()
    {
        return this._plusMinusSrc_;
    }

    public void setPlusMinusSrc(PPlusMinusExpr node)
    {
        if(this._plusMinusSrc_ != null)
        {
            this._plusMinusSrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusSrc_ = node;
    }

    public TNotEquals getNotEquals()
    {
        return this._notEquals_;
    }

    public void setNotEquals(TNotEquals node)
    {
        if(this._notEquals_ != null)
        {
            this._notEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notEquals_ = node;
    }

    public PPlusMinusExpr getPlusMinusTarget()
    {
        return this._plusMinusTarget_;
    }

    public void setPlusMinusTarget(PPlusMinusExpr node)
    {
        if(this._plusMinusTarget_ != null)
        {
            this._plusMinusTarget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusTarget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusMinusSrc_)
            + toString(this._notEquals_)
            + toString(this._plusMinusTarget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusMinusSrc_ == child)
        {
            this._plusMinusSrc_ = null;
            return;
        }

        if(this._notEquals_ == child)
        {
            this._notEquals_ = null;
            return;
        }

        if(this._plusMinusTarget_ == child)
        {
            this._plusMinusTarget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusMinusSrc_ == oldChild)
        {
            setPlusMinusSrc((PPlusMinusExpr) newChild);
            return;
        }

        if(this._notEquals_ == oldChild)
        {
            setNotEquals((TNotEquals) newChild);
            return;
        }

        if(this._plusMinusTarget_ == oldChild)
        {
            setPlusMinusTarget((PPlusMinusExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
