/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class APlusMinusExprLogicalExpr extends PLogicalExpr
{
    private PPlusMinusExpr _plusMinusExpr_;

    public APlusMinusExprLogicalExpr()
    {
        // Constructor
    }

    public APlusMinusExprLogicalExpr(
        @SuppressWarnings("hiding") PPlusMinusExpr _plusMinusExpr_)
    {
        // Constructor
        setPlusMinusExpr(_plusMinusExpr_);

    }

    @Override
    public Object clone()
    {
        return new APlusMinusExprLogicalExpr(
            cloneNode(this._plusMinusExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusMinusExprLogicalExpr(this);
    }

    public PPlusMinusExpr getPlusMinusExpr()
    {
        return this._plusMinusExpr_;
    }

    public void setPlusMinusExpr(PPlusMinusExpr node)
    {
        if(this._plusMinusExpr_ != null)
        {
            this._plusMinusExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusMinusExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusMinusExpr_ == child)
        {
            this._plusMinusExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusMinusExpr_ == oldChild)
        {
            setPlusMinusExpr((PPlusMinusExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
