/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASubtractionPlusMinusExpr extends PPlusMinusExpr
{
    private PPlusMinusExpr _plusMinusExprSrc_;
    private TMinus _minus_;
    private PMultDivModExpr _multDivModTarget_;

    public ASubtractionPlusMinusExpr()
    {
        // Constructor
    }

    public ASubtractionPlusMinusExpr(
        @SuppressWarnings("hiding") PPlusMinusExpr _plusMinusExprSrc_,
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PMultDivModExpr _multDivModTarget_)
    {
        // Constructor
        setPlusMinusExprSrc(_plusMinusExprSrc_);

        setMinus(_minus_);

        setMultDivModTarget(_multDivModTarget_);

    }

    @Override
    public Object clone()
    {
        return new ASubtractionPlusMinusExpr(
            cloneNode(this._plusMinusExprSrc_),
            cloneNode(this._minus_),
            cloneNode(this._multDivModTarget_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubtractionPlusMinusExpr(this);
    }

    public PPlusMinusExpr getPlusMinusExprSrc()
    {
        return this._plusMinusExprSrc_;
    }

    public void setPlusMinusExprSrc(PPlusMinusExpr node)
    {
        if(this._plusMinusExprSrc_ != null)
        {
            this._plusMinusExprSrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusMinusExprSrc_ = node;
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PMultDivModExpr getMultDivModTarget()
    {
        return this._multDivModTarget_;
    }

    public void setMultDivModTarget(PMultDivModExpr node)
    {
        if(this._multDivModTarget_ != null)
        {
            this._multDivModTarget_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDivModTarget_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plusMinusExprSrc_)
            + toString(this._minus_)
            + toString(this._multDivModTarget_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plusMinusExprSrc_ == child)
        {
            this._plusMinusExprSrc_ = null;
            return;
        }

        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._multDivModTarget_ == child)
        {
            this._multDivModTarget_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plusMinusExprSrc_ == oldChild)
        {
            setPlusMinusExprSrc((PPlusMinusExpr) newChild);
            return;
        }

        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._multDivModTarget_ == oldChild)
        {
            setMultDivModTarget((PMultDivModExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
