/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnaryNotUnitaryExpr extends PUnitaryExpr
{
    private TNot _not_;
    private PUnitaryExpr _unitaryExpr_;

    public AUnaryNotUnitaryExpr()
    {
        // Constructor
    }

    public AUnaryNotUnitaryExpr(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PUnitaryExpr _unitaryExpr_)
    {
        // Constructor
        setNot(_not_);

        setUnitaryExpr(_unitaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryNotUnitaryExpr(
            cloneNode(this._not_),
            cloneNode(this._unitaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryNotUnitaryExpr(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PUnitaryExpr getUnitaryExpr()
    {
        return this._unitaryExpr_;
    }

    public void setUnitaryExpr(PUnitaryExpr node)
    {
        if(this._unitaryExpr_ != null)
        {
            this._unitaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unitaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._unitaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._unitaryExpr_ == child)
        {
            this._unitaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._unitaryExpr_ == oldChild)
        {
            setUnitaryExpr((PUnitaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
