/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnaryMinusUnitaryExpr extends PUnitaryExpr
{
    private TMinus _minus_;
    private PUnitaryExpr _unitaryExpr_;

    public AUnaryMinusUnitaryExpr()
    {
        // Constructor
    }

    public AUnaryMinusUnitaryExpr(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PUnitaryExpr _unitaryExpr_)
    {
        // Constructor
        setMinus(_minus_);

        setUnitaryExpr(_unitaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryMinusUnitaryExpr(
            cloneNode(this._minus_),
            cloneNode(this._unitaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryMinusUnitaryExpr(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PUnitaryExpr getUnitaryExpr()
    {
        return this._unitaryExpr_;
    }

    public void setUnitaryExpr(PUnitaryExpr node)
    {
        if(this._unitaryExpr_ != null)
        {
            this._unitaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unitaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._unitaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._unitaryExpr_ == child)
        {
            this._unitaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._unitaryExpr_ == oldChild)
        {
            setUnitaryExpr((PUnitaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
