/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnaryPlusUnitaryExpr extends PUnitaryExpr
{
    private TPlus _plus_;
    private PUnitaryExpr _unitaryExpr_;

    public AUnaryPlusUnitaryExpr()
    {
        // Constructor
    }

    public AUnaryPlusUnitaryExpr(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PUnitaryExpr _unitaryExpr_)
    {
        // Constructor
        setPlus(_plus_);

        setUnitaryExpr(_unitaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryPlusUnitaryExpr(
            cloneNode(this._plus_),
            cloneNode(this._unitaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryPlusUnitaryExpr(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PUnitaryExpr getUnitaryExpr()
    {
        return this._unitaryExpr_;
    }

    public void setUnitaryExpr(PUnitaryExpr node)
    {
        if(this._unitaryExpr_ != null)
        {
            this._unitaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unitaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._unitaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._unitaryExpr_ == child)
        {
            this._unitaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._unitaryExpr_ == oldChild)
        {
            setUnitaryExpr((PUnitaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
