/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnitaryExprMultDivModExpr extends PMultDivModExpr
{
    private PUnitaryExpr _unitaryExpr_;

    public AUnitaryExprMultDivModExpr()
    {
        // Constructor
    }

    public AUnitaryExprMultDivModExpr(
        @SuppressWarnings("hiding") PUnitaryExpr _unitaryExpr_)
    {
        // Constructor
        setUnitaryExpr(_unitaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new AUnitaryExprMultDivModExpr(
            cloneNode(this._unitaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnitaryExprMultDivModExpr(this);
    }

    public PUnitaryExpr getUnitaryExpr()
    {
        return this._unitaryExpr_;
    }

    public void setUnitaryExpr(PUnitaryExpr node)
    {
        if(this._unitaryExpr_ != null)
        {
            this._unitaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unitaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unitaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unitaryExpr_ == child)
        {
            this._unitaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unitaryExpr_ == oldChild)
        {
            setUnitaryExpr((PUnitaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
