/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexer;

import java.io.*;
import node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            @SuppressWarnings("hiding") Token token = new56(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            @SuppressWarnings("hiding") Token token = new57(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 58:
                        {
                            @SuppressWarnings("hiding") Token token = new58(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 59:
                        {
                            @SuppressWarnings("hiding") Token token = new59(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComment(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStringLiteral(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCharLiteral(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscapeStringLiteral(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscape(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPlus(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMinus(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessThan(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLessThanOrEq(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreaterThan(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TGreaterThanOrEq(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEquals(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAnd(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOr(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNot(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TColon(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSemicolon(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComma(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLPar(line, pos); }
    Token new21(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRPar(line, pos); }
    Token new22(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBrace(line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBrace(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLBkt(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRBkt(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNotEquals(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEqualTo(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPointer(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDot(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TModulo(line, pos); }
    Token new31(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloatLit(text, line, pos); }
    Token new32(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhiteSpace(text, line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBool(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBreak(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TChar(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TContinue(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TKclass(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDo(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TElse(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalse(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFloat(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIf(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInt(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNew(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNull(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrivate(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProtected(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPublic(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReturn(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStatic(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TStruct(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TThis(line, pos); }
    Token new55(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTrue(line, pos); }
    Token new56(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TWhile(line, pos); }
    Token new57(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVoid(line, pos); }
    Token new58(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIntegerLiteral(text, line, pos); }
    Token new59(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdentifier(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {12, 12, 3}, {13, 13, 4}, {32, 32, 5}, {33, 33, 6}, {34, 34, 7}, {37, 37, 8}, {38, 38, 9}, {39, 39, 10}, {40, 40, 11}, {41, 41, 12}, {42, 42, 13}, {43, 43, 14}, {44, 44, 15}, {45, 45, 16}, {46, 46, 17}, {47, 47, 18}, {48, 48, 19}, {49, 57, 20}, {58, 58, 21}, {59, 59, 22}, {60, 60, 23}, {61, 61, 24}, {62, 62, 25}, {65, 90, 26}, {91, 91, 27}, {93, 93, 28}, {95, 95, 26}, {97, 97, 26}, {98, 98, 29}, {99, 99, 30}, {100, 100, 31}, {101, 101, 32}, {102, 102, 33}, {103, 104, 26}, {105, 105, 34}, {106, 109, 26}, {110, 110, 35}, {111, 111, 26}, {112, 112, 36}, {113, 113, 26}, {114, 114, 37}, {115, 115, 38}, {116, 116, 39}, {117, 117, 26}, {118, 118, 40}, {119, 119, 41}, {120, 122, 26}, {123, 123, 42}, {124, 124, 43}, {125, 125, 44}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 45}, {12, 32, -2}, },
            {{9, 32, -2}, },
            {{61, 61, 46}, },
            {{0, 9, 47}, {11, 12, 47}, {14, 33, 47}, {34, 34, 48}, {35, 91, 47}, {92, 92, 49}, {93, 65535, 47}, },
            {},
            {{38, 38, 50}, },
            {{32, 32, 51}, {33, 33, 52}, {34, 34, 53}, {35, 35, 54}, {36, 36, 55}, {37, 37, 56}, {38, 38, 57}, {40, 40, 58}, {41, 41, 59}, {42, 42, 60}, {43, 43, 61}, {44, 44, 62}, {45, 45, 63}, {46, 46, 64}, {47, 47, 65}, {48, 57, 66}, {58, 58, 67}, {59, 59, 68}, {60, 60, 69}, {61, 61, 70}, {62, 62, 71}, {63, 63, 72}, {64, 64, 73}, {65, 90, 74}, {91, 91, 75}, {92, 92, 76}, {93, 93, 77}, {94, 94, 78}, {95, 95, 79}, {96, 96, 80}, {97, 122, 81}, {123, 123, 82}, {124, 124, 83}, {125, 125, 84}, {126, 126, 85}, },
            {},
            {},
            {},
            {},
            {},
            {{62, 62, 86}, },
            {{48, 57, 87}, },
            {{42, 42, 88}, {47, 47, 89}, },
            {{46, 46, 90}, {48, 57, 19}, },
            {{46, 46, 90}, {48, 57, 91}, },
            {},
            {},
            {{61, 61, 92}, },
            {{61, 61, 93}, },
            {{61, 61, 94}, },
            {{48, 57, 95}, {65, 90, 95}, {95, 95, 95}, {97, 122, 95}, },
            {},
            {},
            {{48, 95, -28}, {97, 110, 95}, {111, 111, 96}, {112, 113, 95}, {114, 114, 97}, {115, 122, 95}, },
            {{48, 95, -28}, {97, 103, 95}, {104, 104, 98}, {105, 107, 95}, {108, 108, 99}, {109, 110, 95}, {111, 111, 100}, {112, 122, 95}, },
            {{48, 110, -31}, {111, 111, 101}, {112, 122, 95}, },
            {{48, 95, -28}, {97, 107, 95}, {108, 108, 102}, {109, 122, 95}, },
            {{48, 95, -28}, {97, 97, 103}, {98, 107, 95}, {108, 108, 104}, {109, 122, 95}, },
            {{48, 95, -28}, {97, 101, 95}, {102, 102, 105}, {103, 109, 95}, {110, 110, 106}, {111, 122, 95}, },
            {{48, 95, -28}, {97, 100, 95}, {101, 101, 107}, {102, 116, 95}, {117, 117, 108}, {118, 122, 95}, },
            {{48, 95, -28}, {97, 113, 95}, {114, 114, 109}, {115, 116, 95}, {117, 117, 110}, {118, 122, 95}, },
            {{48, 100, -37}, {101, 101, 111}, {102, 122, 95}, },
            {{48, 95, -28}, {97, 115, 95}, {116, 116, 112}, {117, 122, 95}, },
            {{48, 103, -32}, {104, 104, 113}, {105, 113, 95}, {114, 114, 114}, {115, 122, 95}, },
            {{48, 110, -31}, {111, 111, 115}, {112, 122, 95}, },
            {{48, 103, -32}, {104, 104, 116}, {105, 122, 95}, },
            {},
            {{124, 124, 117}, },
            {},
            {{9, 32, -2}, },
            {},
            {{0, 65535, -9}, },
            {},
            {{0, 33, -9}, {34, 34, 118}, {35, 38, 47}, {39, 39, 119}, {40, 91, 47}, {92, 92, 120}, {93, 97, 47}, {98, 98, 121}, {99, 101, 47}, {102, 102, 122}, {103, 109, 47}, {110, 110, 123}, {111, 113, 47}, {114, 114, 124}, {115, 115, 47}, {116, 116, 125}, {117, 65535, 47}, },
            {},
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{34, 34, 127}, {39, 39, 128}, {92, 92, 129}, {98, 98, 130}, {102, 102, 131}, {110, 110, 132}, {114, 114, 133}, {116, 116, 134}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {{39, 39, 126}, },
            {},
            {{48, 57, 87}, {69, 69, 135}, {101, 101, 136}, },
            {{0, 41, 137}, {42, 42, 138}, {43, 65535, 137}, },
            {{0, 9, 139}, {10, 10, 140}, {11, 12, 139}, {13, 13, 141}, {14, 65535, 139}, },
            {{48, 57, 142}, {69, 101, -89}, },
            {{46, 57, -22}, },
            {},
            {},
            {},
            {{48, 122, -28}, },
            {{48, 110, -31}, {111, 111, 143}, {112, 122, 95}, },
            {{48, 100, -37}, {101, 101, 144}, {102, 122, 95}, },
            {{48, 95, -28}, {97, 97, 145}, {98, 122, 95}, },
            {{48, 95, -28}, {97, 97, 146}, {98, 122, 95}, },
            {{48, 95, -28}, {97, 109, 95}, {110, 110, 147}, {111, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 95, -28}, {97, 114, 95}, {115, 115, 148}, {116, 122, 95}, },
            {{48, 107, -34}, {108, 108, 149}, {109, 122, 95}, },
            {{48, 110, -31}, {111, 111, 150}, {112, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 115, -40}, {116, 116, 151}, {117, 122, 95}, },
            {{48, 95, -28}, {97, 118, 95}, {119, 119, 152}, {120, 122, 95}, },
            {{48, 107, -34}, {108, 108, 153}, {109, 122, 95}, },
            {{48, 95, -28}, {97, 104, 95}, {105, 105, 154}, {106, 110, 95}, {111, 111, 155}, {112, 122, 95}, },
            {{48, 95, -28}, {97, 97, 95}, {98, 98, 156}, {99, 122, 95}, },
            {{48, 115, -40}, {116, 116, 157}, {117, 122, 95}, },
            {{48, 95, -28}, {97, 97, 158}, {98, 113, 95}, {114, 114, 159}, {115, 122, 95}, },
            {{48, 104, -111}, {105, 105, 160}, {106, 122, 95}, },
            {{48, 95, -28}, {97, 116, 95}, {117, 117, 161}, {118, 122, 95}, },
            {{48, 104, -111}, {105, 105, 162}, {106, 122, 95}, },
            {{48, 104, -111}, {105, 105, 163}, {106, 122, 95}, },
            {},
            {{0, 9, 164}, {11, 12, 164}, {14, 33, 164}, {34, 34, 165}, {35, 91, 164}, {92, 92, 166}, {93, 65535, 164}, },
            {{0, 65535, -9}, },
            {{0, 65535, -51}, },
            {{0, 65535, -9}, },
            {{0, 65535, -9}, },
            {{0, 65535, -9}, },
            {{0, 65535, -9}, },
            {{0, 65535, -9}, },
            {},
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{39, 39, 167}, },
            {{43, 43, 168}, {45, 45, 169}, {48, 57, 170}, },
            {{43, 57, -137}, },
            {{0, 65535, -90}, },
            {{0, 41, 171}, {42, 42, 138}, {43, 46, 171}, {47, 47, 172}, {48, 65535, 171}, },
            {{0, 65535, -91}, },
            {},
            {{10, 10, 173}, },
            {{48, 101, -92}, },
            {{48, 107, -34}, {108, 108, 174}, {109, 122, 95}, },
            {{48, 95, -28}, {97, 97, 175}, {98, 122, 95}, },
            {{48, 113, -38}, {114, 114, 176}, {115, 122, 95}, },
            {{48, 114, -104}, {115, 115, 177}, {116, 122, 95}, },
            {{48, 114, -104}, {115, 115, 178}, {116, 116, 179}, {117, 122, 95}, },
            {{48, 100, -37}, {101, 101, 180}, {102, 122, 95}, },
            {{48, 114, -104}, {115, 115, 181}, {116, 122, 95}, },
            {{48, 95, -28}, {97, 97, 182}, {98, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 107, -34}, {108, 108, 183}, {109, 122, 95}, },
            {{48, 95, -28}, {97, 117, 95}, {118, 118, 184}, {119, 122, 95}, },
            {{48, 115, -40}, {116, 116, 185}, {117, 122, 95}, },
            {{48, 107, -34}, {108, 108, 186}, {109, 122, 95}, },
            {{48, 116, -116}, {117, 117, 187}, {118, 122, 95}, },
            {{48, 115, -40}, {116, 116, 188}, {117, 122, 95}, },
            {{48, 104, -111}, {105, 105, 189}, {106, 116, 95}, {117, 117, 190}, {118, 122, 95}, },
            {{48, 114, -104}, {115, 115, 191}, {116, 122, 95}, },
            {{48, 100, -37}, {101, 101, 192}, {102, 122, 95}, },
            {{48, 95, -28}, {97, 99, 95}, {100, 100, 193}, {101, 122, 95}, },
            {{48, 107, -34}, {108, 108, 194}, {109, 122, 95}, },
            {{0, 65535, -120}, },
            {},
            {{0, 33, -120}, {34, 34, 195}, {35, 38, 164}, {39, 39, 196}, {40, 91, 164}, {92, 92, 197}, {93, 97, 164}, {98, 98, 198}, {99, 101, 164}, {102, 102, 199}, {103, 109, 164}, {110, 110, 200}, {111, 113, 164}, {114, 114, 201}, {115, 115, 164}, {116, 116, 202}, {117, 65535, 164}, },
            {},
            {{48, 57, 170}, },
            {{48, 57, 170}, },
            {{48, 57, 170}, },
            {{0, 41, 203}, {42, 42, 204}, {43, 65535, 203}, },
            {},
            {},
            {{48, 122, -28}, },
            {{48, 95, -28}, {97, 106, 95}, {107, 107, 205}, {108, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 114, -104}, {115, 115, 206}, {116, 122, 95}, },
            {{48, 115, -40}, {116, 116, 207}, {117, 122, 95}, },
            {{48, 104, -111}, {105, 105, 208}, {106, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 100, -37}, {101, 101, 209}, {102, 122, 95}, },
            {{48, 115, -40}, {116, 116, 210}, {117, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 95, -28}, {97, 97, 211}, {98, 122, 95}, },
            {{48, 100, -37}, {101, 101, 212}, {102, 122, 95}, },
            {{48, 104, -111}, {105, 105, 213}, {106, 122, 95}, },
            {{48, 113, -38}, {114, 114, 214}, {115, 122, 95}, },
            {{48, 104, -111}, {105, 105, 215}, {106, 122, 95}, },
            {{48, 109, -102}, {110, 110, 216}, {111, 122, 95}, },
            {{48, 95, -28}, {97, 98, 95}, {99, 99, 217}, {100, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 100, -37}, {101, 101, 218}, {102, 122, 95}, },
            {{0, 65535, -120}, },
            {{0, 65535, -120}, },
            {{0, 65535, -168}, },
            {{0, 65535, -120}, },
            {{0, 65535, -120}, },
            {{0, 65535, -120}, },
            {{0, 65535, -120}, },
            {{0, 65535, -120}, },
            {{0, 65535, -173}, },
            {{0, 41, 171}, {42, 42, 204}, {43, 65535, -140}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 109, -102}, {110, 110, 219}, {111, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 115, -40}, {116, 116, 220}, {117, 122, 95}, },
            {{48, 98, -192}, {99, 99, 221}, {100, 122, 95}, },
            {{48, 98, -192}, {99, 99, 222}, {100, 122, 95}, },
            {{48, 109, -102}, {110, 110, 223}, {111, 122, 95}, },
            {{48, 98, -192}, {99, 99, 224}, {100, 122, 95}, },
            {{48, 95, -28}, {97, 102, 95}, {103, 103, 225}, {104, 122, 95}, },
            {{48, 115, -40}, {116, 116, 226}, {117, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 116, -116}, {117, 117, 227}, {118, 122, 95}, },
            {{48, 100, -37}, {101, 101, 228}, {102, 122, 95}, },
            {{48, 115, -40}, {116, 116, 229}, {117, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 122, -28}, },
            {{48, 100, -37}, {101, 101, 230}, {102, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 100, -37}, {101, 101, 231}, {102, 122, 95}, },
            {{48, 122, -28}, },
            {{48, 99, -164}, {100, 100, 232}, {101, 122, 95}, },
            {{48, 122, -28}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {32, 32, 32, 32, 32, 32, 16, -1, 30, -1, -1, 20, 21, 7, 5, 19, 6, 29, 8, -1, 58, 17, 18, 9, 27, 11, 59, 24, 25, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 22, -1, 23, 32, 26, -1, 1, -1, 14, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28, 31, -1, -1, 31, 58, 10, 13, 12, 59, 59, 59, 59, 59, 59, 39, 59, 59, 59, 43, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 15, 1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 31, 59, 59, 59, 59, 59, 59, 59, 59, 44, 45, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, -1, 3, -1, 4, -1, -1, 31, -1, 0, 0, 33, 59, 35, 59, 59, 59, 40, 59, 59, 46, 59, 59, 59, 59, 59, 59, 59, 54, 55, 57, 59, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1, 34, 38, 36, 59, 41, 42, 59, 59, 59, 59, 59, 59, 59, 56, 59, 59, 59, 49, 50, 51, 52, 53, 59, 47, 59, 37, 59, 48, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
